# Generated by Django 5.2.5 on 2025-08-22 15:40

import django_enumfield.db.fields
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=project.models.OrderStatus),
        ),
        migrations.AlterField(
            model_name='project',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
